### ISSUE TITLE
Cannot find module 'utils' and "grunt-jsdoc-to-markdown"

### ISSUE THREAD

**Issue by julmot** [CleverStack/angular-seed#88] opened 2015-06-21 20:03 UTC
Hello,

I've just installed the angular-seed like it's described in the documentation. Unfortunately I get two error messages:
![cleverstack](https://cloud.githubusercontent.com/assets/8310677/8273168/0b06136c-1861-11e5-93bd-de975024be34.png)
What is the correct way to solve this problem?
Notice: I didn't installed a customized version of NodeJS. If the installation documentation doesn't work in a raw NodeJS-installation, maybe it should be documented what kind of modules are required to install this boilerplate.

**Comment by pilsy** [comment] 2015-06-23 04:25
Hi @julmot 

To me this looks like you have not run `clever setup` - if you type `npm ls` what is the output? also any of the `clever` commands have the `-v` or `--verbose` option ... ie `clever setup -v`

The utils part could be related to not having your NODE_PATH set, but i'm not 100% sure with seeing only the output you posted (can you please use the `-v` option?)

In general to set your NODE_PATH:

### On Mac/Linux:
`export NODE_PATH=./lib/:./modules/`

### On Windows:
`set NODE_PATH=./lib/;./modules/`

**Comment by pilsy** [comment] 2015-07-21 11:07
Confirmed fixed via https://github.com/CleverStack/cleverstack-cli/issues/76#issuecomment-121777570 and others

**Closed by pilsy** 2015-07-21 11:07 UTC
Labels: question
